- name: Task Block Demo Playbook
  hosts: spine01
  tasks:
	-	name: First Task Outside Block
		debug:
        msg: "I am outside Block"	
  -	name: Block for installing Web Server 
		block: ## Block Starts
      - name: label the management interface (eth0)
        vyos_interface:
          name: eth0
          description: management
      - name: set banner motd
        vyos_banner:
          banner: pre-login
          text: "Unuauthorized access to this device is prohibited"
          state: present
      - name: Extra task in Block
        debug:
          msg: "Extra task"
    when:  ansible_network_os == "vyos" ## Block Condition
    rescue: ## Used for rollback failed process if block task fail
    	- name: Rollback your tasks
      	debug:
        	msg: "Rollback your stuff"
    always: ## Always run whether block success or failed
    	- name: Inform Stake Holders
      	debug:
        	msg: "Mail to Everyone please"
  - name: Second Task Outside Block
    debug:
        msg: "I am outside Block too"

