- name: Debug Strategy Playbook
  hosts: leaf01
  strategy: debug
  tasks:
  - name: I am setting desc
    vyos_interface:
      name: eth000
      desc: "Something"
# task.args
# task.args['name']='eth0'
# task.args
# redo

  - name: Let's set banner
    vyos_banner:
      banner: preeeee-login
      textttttt: "some banner"
# task.args
# task.args['banner']='pre-login'          	## value correction
# task.args['text']='some banner'      		## add new option
# del(task.args['textttttt'])     		## delete current wrong option

