- name: Tags Demo Playbook
  hosts: leaf01.lab.example.com
  tasks:
  - name: Task for Dev 1  
    debug:
      msg: "Dev Task 1"
    tags:
    - test
    - dev
  - name: Task for Prod 
    debug:
      msg: "Prod Task 1"
    tags:
    - prod
  - name: Task that always execute
    debug:
      msg: "Always task inform Clients"
    tags:
    - always
  - name: Without a Tag
    debug:
      msg: "Untagged Task"
  - name: Emergency Task
    debug:
      msg: "Destroy Datacenter"
    tags:
    - never
  - name: Task for Dev 2
    debug:
      msg: "Dev Task 2"
    tags:
    - dev
  - name: Task for Prod 2
    debug:
      msg: "Prod Task 2"
    tags:
    - prod
