- name: Tags Demo Playbook
  hosts: servera.lab.example.com
  vars_prompt:
  - name: username
    prompt: "What is your username?"
    private: no

  - name: password
    prompt: "What is your password?"
  tasks:
  - name: Print Task 1  
    debug:
      msg: "Debug Task 1 {{username}} {{password|password_hash('sha512')}}"
                                                                       
                                                                       
                                                                       
                                                                       
                                                                       
