- name: break up the layer 3 network
  hosts: network
  vars_files:
  - vars/breakup-data.yml

  tasks:
  - name: remove the legacy layer3 data
    vyos_l3_interface:
      aggregate: "{{ remove_layer3_data[inventory_hostname] }}"
      state: absent
    when: ansible_network_os == 'vyos'

  - name: configure interface descriptions
    vyos_interface:
      name: "{{ item.key }}"
      description: "{{ item.value.description }}"
    with_dict: "{{ interface_data[inventory_hostname] }}"
    when: ansible_network_os == 'vyos'

  - name: configure layer 3
    vyos_l3_interface:
      aggregate: "{{ layer3_data[inventory_hostname] }}"
    when: ansible_network_os == 'vyos'

  - name: configure interface descriptions
    ios_interface:
      name: "{{ item.key }}"
      description: "{{ item.value.description }}"
    with_dict: "{{ interface_data[inventory_hostname] }}"
    when: ansible_network_os == 'ios'

  - name: configure layer 3
    ios_l3_interface:
      aggregate: "{{ layer3_data[inventory_hostname] }}"
    when: ansible_network_os == 'ios'
