- name: verify connectivity end-to-end
  hosts: access-layer
  vars_files:
  - vars/ping-srcdst.yml
  tasks:
  - name: run ping commands on VyOS access layer device
  # this runs a ping command across the link
    vyos_command:
      commands:
      - ping {{ item.dst }} interface {{ item.src }} count {{ pingcount }}
    register: ping_result
    loop: "{{ ping_data[inventory_hostname] }}"
    when: ansible_network_os == 'vyos'
    # registering within loop associates values with varname.results

  - name: looped assertion of ping results from VyOS access layer device
    assert:
      that: "', 0% packet loss' in item.stdout[0]"
    loop: "{{ ping_result.results }}"
    when: ansible_network_os == 'vyos'

  - name: prime IOS arp cache
    ios_command:
      commands:
      - ping {{ item.dst }} source {{ item.src }} repeat 1
    loop: "{{ ping_data[inventory_hostname] }}"
    when: ansible_network_os == 'ios'

  - name: "run ping commands on IOS access layer device {{ inventory_hostname }}"
    ios_command:
      commands:
      - ping {{ item.dst }} source {{ item.src }} repeat {{ pingcount }}
    register: ping_result
    loop: "{{ ping_data[inventory_hostname] }}"
    when: ansible_network_os == 'ios'

  - name: looped assertion of ping results from IOS access layer device
    assert:
      that: "'Success rate is 100 percent' in item.stdout[0]"
    loop: "{{ ping_result.results }}"
    when: ansible_network_os == 'ios'
