- name: play to shutdown an interface
  # Required arguments: target, intf
  hosts: "{{ target }}"
  tasks:

  - name: disable interface {{ intf }} on a VyOS box
    vyos_interface:
      name: "{{ intf }}"
      enabled: False
    when: ansible_network_os == 'vyos'

  - name: disable interface {{ intf }} on an IOS box
    ios_interface:
      name: "{{ intf }}"
      enabled: False
    when: ansible_network_os == 'ios'
